name: Build and Release

on:
  release:
    types: [published]

env:
  APP_NAME: koreader-companion

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      
      - name: Build app tarball
        run: make appstore
      
      - name: Upload to GitHub release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: build/artifacts/appstore/${{ env.APP_NAME }}.tar.gz