name: Build and Release

on:
  release:
    types: [published]

env:
  APP_NAME: koreader_companion

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      
      - name: Setup PHP
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2
        with:
          php-version: '8.1'
          extensions: zip
      
      - name: Build app tarball
        run: make appstore
      
      - name: Upload to GitHub release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        id: github_release
        with:
          files: build/artifacts/appstore/${{ env.APP_NAME }}.tar.gz
      
      - name: Upload app to Nextcloud appstore
        uses: R0Wi/nextcloud-appstore-push-action@cec25fa221c6b2a82701dca2a9455b39f9f7b252 # latest commit
        with:
          app_name: ${{ env.APP_NAME }}
          appstore_token: ${{ secrets.APPSTORE_TOKEN }}
          download_url: ${{ fromJSON(steps.github_release.outputs.assets)[0].browser_download_url }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          nightly: ${{ github.event.release.prerelease }}